name: wallet
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.1.0
  flutter_svg: ^0.10.3
  flutter_screenutil: ^0.5.0
  barcode_scan: ^0.0.4
  qr_flutter: ^1.1.6
  connectivity: ^0.4.2
  shared_preferences: ^0.5.1+1
  flutter_i18n: ^0.6.2
  intl: ^0.15.7
  common_utils: ^1.0.9
  rubber: ^0.2.6
  fluttertoast: ^3.0.1
  intl_translation: ^0.17.3
  sms: ^0.2.4
  flutter_easyrefresh: ^1.2.7
  decimal: ^0.3.0
  flutter_dotenv: ^2.0.1
  url_launcher: ^5.0.2
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/json/AreaCode.json
  - assets/images/
  - assets/images/common/
  - assets/images/common/2.0x/
  - assets/images/common/3.0x/
  - assets/images/home/
  - assets/images/home/2.0x/
  - assets/images/home/3.0x/
  - assets/images/transfer/
  - assets/images/transfer/2.0x/
  - assets/images/transfer/3.0x/
  - assets/images/user/
  - assets/images/user/2.0x/
  - assets/images/user/3.0x/
  - assets/images/receipt/
  - assets/images/login/
  - assets/images/financial/
  # 多语言
  - assets/flutter_i18n/en.json
  - assets/flutter_i18n/zh.json
  - assets/flutter_i18n/ko.json
  # 环境变量文件
  - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
